version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn run ci:publish
      - run: ./publish.sh
