export {
  AGENTS_ROW_EMAIL,
  AGENTS_ROW_FULL_NAME,
  AGENTS_ROW_SSN,
  AUTHORIZED_BY_COMPANY_FIELDS,
} from './src/fields/agents';
export {
  FREE_TEXT_PURPOSES,
  FREE_TEXT_PURPOSES_ORIGIN_OF_THE_FUNDS,
  FREE_TEXT_PURPOSES_PURPOSE_OF_USING_REDEYES_SERVICES,
  ORIGIN_CAPITAL_GAIN_FROM_COMPANY_DIVESTMENT,
  ORIGIN_CAPITAL_GAIN_FROM_REAL_ESTATE,
  ORIGIN_HERITAGE,
  ORIGIN_INSURANCE_MONIES,
  ORIGIN_OTHER,
  ORIGIN_SALARY,
  ORIGIN_SAVINGS,
  PURPOSE_INVESTMENTS_TO_MAXIMIZE_PORTFOLIO_DIVERSITY,
  PURPOSE_OTHER,
  PURPOSE_SAVINGS_OTHER_THAN_RETIREMENT,
  PURPOSE_SAVINGS_RETIREMENT,
  PURPOSE_SPECULATION,
} from './src/fields/freeTextPurposes';
export {
  AMOUNT_LABELS,
  FREQUENCY_LABELS,
  HORIZON_LABELS,
  PURPOSE_AND_NATURE_ENTIRE_VALUE_OF_YOUR_INVESTMENT_PORTFOLIO,
  PURPOSE_AND_NATURE_EXPECT_TO_INVEST_IN_FINANCIAL_INSTRUMENTS,
  PURPOSE_AND_NATURE_INVESTMENT_FREQUENCY,
  PURPOSE_AND_NATURE_INVESTMENT_HORIZON,
  PURPOSE_AND_NATURE_KEYS,
} from './src/fields/purposeAndNature';
export {
  TAX_LIABILITY_FALSE,
  TAX_LIABILITY_TRUE,
  TAX_LIABILITY_UNSET,
} from './src/fields/taxLiability';

export {
  COMPANY_FUNNEL,
  KYC_TYPE_FUNNEL_MAP,
  PAGE_COMPANY_AGENTS,
  PAGE_COMPANY_CONTACT,
  PAGE_COMPANY_DETAILS,
  PAGE_PEP,
  PAGE_PERSON_NATIONALITY,
  PAGE_PERSON_PERSONAL,
  PAGE_PURPOSE_AND_NATURE,
  PAGE_SIGN,
  PAGE_START,
  PAGE_TAX,
  PAGE_TERMS,
  PAGE_UBO,
  PERSON_FUNNEL,
  getNextPageIdInFunnel,
  getFunnelPageById,
} from './src/funnels';
export { KYC_TYPE_COMPANY, KYC_TYPE_PERSON } from './src/kycTypes';

export {
  BENEFICIAL_OWNERS_ROW_FULL_NAME,
  BENEFICIAL_OWNERS_ROW_BIRTH_DATE,
  BENEFICIAL_OWNERS_ROW_NATIONALITY,
  BENEFICIAL_OWNERS_ROW_ADDRESS,
  BENEFICIAL_OWNERS_ROW_OWNERSHIP,
  BENEFICIAL_OWNERS_ROW_VOTING_RIGHT,
  BENEFICIAL_OWNERS_ROW_IS_PEP,
  BENEFICIAL_OWNERS_FIELDS,
} from './src/fields/beneficialOwners';

export {
  PEP_HAS_BEEN_A_PEP_DURING_THE_LAST_2_YEARS,
  PEP_A_BENEFICIAL_OWNER_TO_ME_THE_CLIENT_IS_OR_HAS_DURING_THE_LAST_2_YEARS_BEEN_A_PEP,
  PEP_HAS_DURING_THE_PAST_2_YEARS_BEEN_A_FAMILY_MEMBER_OT_A_PEP,
  PEP_HAS_DURING_THE_PAST_2_YEARS_BEEN_A_CLOSE_ASSOCIATE_TO_A_PEP,
  PEP_NONE_OF_THE_ABOVE,
  PEP_FIELDS,
} from './src/fields/pep';

export {
  CLIENT_FULFILLMENTS_SWEDISH_AUTHORITY,
  CLIENT_FULFILLMENTS_ENGAGED_IN,
  CLIENT_FULFILLMENTS_EEA_COMPANY,
  CLIENT_FULFILLMENTS_NONE_OF_THE_ABOVE,
  CLIENT_FULFILLMENTS_FIELDS,
} from './src/fields/clientFulfillments';

export {
  FIELD_PERSONAL_FIRST_NAME,
  FIELD_PERSONAL_LAST_NAME,
  FIELD_PERSONAL_ADDRESS,
  FIELD_PERSONAL_CITY,
  FIELD_PERSONAL_ZIP_CODE,
  FIELD_PERSONAL_COUNTRY,
  FIELD_PERSONAL_EMAIL,
  FIELD_PERSONAL_PHONE_NUMBER,
  PERSONAL_FIELDS,
  FIELD_PERSONAL_BIRTH_DATE,
  FIELD_PERSONAL_SSN,
  FIELD_PERSONAL_CITIZENSHIP,
  FIELD_PERSONAL_COUNTRY_OF_RESIDENCE,
  NATIONALITY_FIELDS,
  FIELD_COMPANY_NAME,
  FIELD_COMPANY_LEI_CODE,
  FIELD_COMPANY_ID,
  FIELD_COMPANY_COUNTRY_OF_INCORPORATION,
  FIELD_COMPANY_STREET_ADDRESS,
  FIELD_COMPANY_ZIP_CODE,
  FIELD_COMPANY_CITY,
  FIELD_COMPANY_COUNTRY,
  FIELD_COMPANY_CONTACT_FIRST_NAME,
  FIELD_COMPANY_CONTACT_LAST_NAME,
  FIELD_COMPANY_CONTACT_EMAIL,
  FIELD_COMPANY_CONTACT_PHONE_NUMBER,
  COMPANY_DETAILS_FIELDS,
  COMPANY_CONTACT_FIELDS,
  FIELDS,
} from './src/fields/form';
